version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@types/node"
    versions:
    - 14.14.37
    - 15.0.0
  - dependency-name: commander
    versions:
    - 7.2.0
  - dependency-name: jasmine
    versions:
    - 3.7.0
  - dependency-name: semantic-release
    versions:
    - 17.4.2
  - dependency-name: "@semantic-release/github"
    versions:
    - 7.2.1
  - dependency-name: husky
    versions:
    - 6.0.0
  - dependency-name: "@semantic-release/npm"
    versions:
    - 7.1.1
  - dependency-name: lint-staged
    versions:
    - 10.5.4
  - dependency-name: y18n
    versions:
    - 4.0.3
  - dependency-name: "@types/jsdom"
    versions:
    - 16.2.10
